version: '3'

services:
  postgres-pjc:
    container_name: postgres    
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "15432:5432"
    volumes:
      - /opt/postgres:/var/lib/postgresql/data 
    networks:
      - network
      
  pgadmin-pjc:
    container_name: pgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "lauremberg@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    ports:
      - "16543:80"
    depends_on:
      - postgres-pjc
    networks:
      - network

  minio-pjc:
    container_name: minio
    image: minio/minio
    ports:
    - "19000:9000"
    volumes:
    - /opt/data:/data
    command: server /data
    networks:
    - network

networks: 
  network:
    driver: bridge
